"""Perfiles MCP versionados — proyección pequeña por dominio (Capability Router Fase 0)."""

from __future__ import annotations

from typing import Any

from raphiia_openai.capability_registry import catalog_fingerprint, log_routing_trace
from raphiia_openai.mcp_catalog import tool_catalog

PROFILES_VERSION = "1.3.0"

# Toolsets pequeños — no reemplazan tools/list global
PROFILES: dict[str, dict[str, Any]] = {
    "contifico_analytics": {
        "label": "Contífico analítico (piloto RO)",
        "model_minimum": "small",
        "max_tools": 12,
        "tools": [
            "mcp_version",
            "diagnose_mcp_session",
            "contifico_analytics_capabilities",
            "contifico_resolve_entity",
            "contifico_query",
            "contifico_get_document",
            "contifico_get_party_360",
            "contifico_explain_metric",
            "get_contifico_bank_balance",
            "contifico_inventory_summary",
        ],
    },
    "quoter": {
        "label": "Cotización + WhatsApp",
        "model_minimum": "small",
        "max_tools": 12,
        "tools": [
            "get_operational_runbooks",
            "sync_quote_sources",
            "resolve_party",
            "resolve_client",
            "create_quote_draft",
            "update_quote_draft",
            "generate_quote_intro",
            "generate_quote_pdf",
            "render_quote_document",
            "send_quote_delivery",
            "get_quote_tracking",
            "send_whatsapp_document",
        ],
    },
    "vero": {
        "label": "Vero — pipeline comercial PC Doctor",
        "model_minimum": "small",
        "max_tools": 15,
        "tools": [
            "vero_dispatch",
            "vero_proactive_briefing",
            "quote_client",
            "invoice_client",
            "technical_report_client",
            "get_commercial_mission",
            "resolve_client",
            "create_quote_draft",
            "update_quote_draft",
            "render_quote_document",
            "send_quote_delivery",
            "create_receivable_from_quote",
            "generate_supervisor_report",
            "get_quote_tracking",
            "send_whatsapp_document",
        ],
    },
    "raul": {
        "label": "Raul — catálogo local Contifico→Mongo",
        "model_minimum": "small",
        "max_tools": 8,
        "tools": [
            "raul_dispatch",
            "raul_catalog_status",
            "raul_hydrate_catalog",
            "product_intelligence",
            "list_local_models",
            "local_model_health",
            "run_local_model",
        ],
    },
    "msp_core": {
        "label": "PC Doctor campo",
        "model_minimum": "small",
        "max_tools": 45,
        "tools": [
            "mcp_version",
            "bootstrap_context",
            "resolve_client",
            "build_client_360_snapshot",
            "create_client_draft",
            "upsert_client",
            "create_site_draft",
            "create_asset_draft",
            "upsert_asset",
            "create_visit_draft",
            "register_client_document",
            "list_client_documents",
            "record_site_network_snapshot",
            "list_site_network_snapshots",
            "create_quote_draft",
            "update_quote_draft",
            "generate_quote_intro",
            "render_quote_document",
            "send_quote_delivery",
        ],
    },
    "accounting": {
        "label": "MOD-ACCOUNTING canónico",
        "model_minimum": "medium",
        "max_tools": 10,
        "tools": [
            "resolve_party",
            "create_payable_draft",
            "upsert_payable",
            "record_payment",
            "create_purchase_draft",
            "receive_goods",
            "create_receivable_draft",
            "create_receivable_from_quote",
            "accounting_summary",
            "record_collection",
        ],
    },
    "communications": {
        "label": "WhatsApp + correo",
        "model_minimum": "small",
        "max_tools": 12,
        "tools": [
            "get_whatsapp_status",
            "send_whatsapp_message",
            "send_whatsapp_document",
            "send_whatsapp_status",
            "get_whatsapp_commands_help",
            "list_whatsapp_groups",
            "resolve_whatsapp_group",
            "save_whatsapp_group",
            "get_email_archive_status",
            "search_email_archive",
            "get_email_archive_message",
            "get_operational_runbooks",
        ],
    },
    "business": {
        "label": "PC Doctor / InnerChispa business compacto",
        "model_minimum": "small",
        "max_tools": 13,
        "tools": [
            "bootstrap_context",
            "route_mcp_tools",
            "dispatch_local_agent",
            "resolve_client",
            "build_client_360_snapshot",
            "create_quote_draft",
            "generate_supervisor_report",
            "run_service_guardian",
            "list_ops_tasks",
            "get_operational_runbooks",
            "get_whatsapp_status",
            "create_agent_message",
        ],
    },
    "home": {
        "label": "Casa / voz local segura",
        "model_minimum": "small",
        "max_tools": 10,
        "tools": [
            "bootstrap_context",
            "route_mcp_tools",
            "ha_list_entities",
            "ha_get_entity",
            "ha_turn_on_light",
            "ha_turn_off_light",
            "get_server_status",
            "dispatch_local_agent",
            "create_agent_message",
        ],
    },
    "funding": {
        "label": "Funding + credits registry",
        "model_minimum": "small",
        "max_tools": 20,
        "tools": [
            "save_funding_program",
            "list_funding_programs",
            "save_funding_application",
            "list_funding_applications",
            "save_funding_credit_account",
            "record_funding_consumption",
            "link_funding_project",
            "get_funding_registry_summary",
            "application_get",
            "application_upsert",
            "application_add_or_update_module",
            "application_upsert_question_answer",
            "application_list_questions",
            "application_search",
            "application_attach_source",
            "application_attach_evidence",
            "application_history",
            "application_mark_submitted",
            "application_export_snapshot",
            "application_migrate_legacy_funding_application",
        ],
    },
    "contifico_read": {
        "label": "Contífico legacy read (compat)",
        "model_minimum": "medium",
        "max_tools": 14,
        "tools": [
            "get_contifico_status",
            "contifico_capabilities",
            "contifico_inventory_summary",
            "resolve_contifico_persona",
            "get_contifico_client_summary",
            "search_contifico_documents",
            "query_contifico_stats",
            "list_contifico_bank_accounts",
            "get_contifico_bank_balance",
            "search_contifico_bank_movements",
            "search_contifico_transactions",
            "get_contifico_sync_status",
            "contifico_query",
            "contifico_get_party_360",
        ],
    },
    "coordination": {
        "label": "RACB coordinación multiagente",
        "model_minimum": "small",
        "max_tools": 12,
        "tools": [
            "get_coordination_live",
            "ack_coordination_revision",
            "list_agent_messages",
            "ack_agent_message",
            "poll_agent_inbox",
            "create_agent_message",
            "list_ops_tasks",
            "create_ops_task",
            "update_ops_task_state",
            "heartbeat_ops_task",
            "complete_ops_task",
            "manage_coordination_lock",
        ],
    },
    "daily_memory": {
        "label": "Daily Life Memory privado y versionado",
        "model_minimum": "medium",
        "max_tools": 14,
        "tools": [
            "save_conversation_batch",
            "finalize_conversation",
            "save_memory",
            "update_memory",
            "search_memory",
            "get_current_state",
            "update_current_state",
            "get_person_context",
            "correct_memory",
            "forget_memory",
            "resolve_pending_item",
            "timeline",
            "get_memory_review_queue",
            "migrate_daily_memory",
        ],
    },
    "owner_read": {
        "label": "Owner lectura compacta — identidad, memoria, estado y contexto",
        "model_minimum": "small",
        "max_tools": 9,
        "tools": [
            "bootstrap_context",
            "search_memory",
            "get_current_state",
            "get_context_summary",
            "get_server_status",
            "get_unified_stack_status",
            "route_mcp_tools",
            "ralfia_status",
            "create_agent_message",
        ],
    },
    "owner_ops": {
        "label": "Owner operaciones seguras — servicios/MSP con confirmacion",
        "model_minimum": "small",
        "max_tools": 14,
        "tools": [
            "bootstrap_context",
            "route_mcp_tools",
            "dispatch_local_agent",
            "run_service_guardian",
            "peer_ops_snapshot",
            "get_server_status",
            "get_infrastructure_status",
            "resolve_client",
            "build_client_360_snapshot",
            "list_client_documents",
            "list_site_network_snapshots",
            "record_site_network_snapshot",
            "list_ops_tasks",
            "create_agent_message",
        ],
    },
    "owner_dev": {
        "label": "Owner development local seguro",
        "model_minimum": "medium",
        "max_tools": 97,
        "tools": [
            "get_coordination_live",
            "bootstrap_context",
            "search_memory",
            "local_model_health",
            "classify_task_runtime",
            "route_ai_task",
            "local_fs_policy",
            "local_fs_list",
            "local_fs_read_file",
            "local_fs_mkdir",
            "local_fs_write_file",
            "local_fs_move_to_quarantine",
            "local_git_init_repo",
            "local_github_status",
            "local_github_create_repo",
            "local_project_bootstrap",
            "local_exec_inspect_repo",
            "local_exec_repo_policy_status",
            "local_exec_repo_authorize",
            "local_exec_repo_revoke",
            "local_exec_prepare_repo",
            "local_exec_hydrate_repo",
            "local_exec_acquire_lock",
            "local_exec_release_lock",
            "local_exec_create_worktree",
            "local_exec_apply_patch",
            "local_exec_write_file",
            "local_exec_run_command_allowlisted",
            "local_exec_commit_branch",
            "local_exec_report_evidence",
            "gcp_auth_bootstrap",
            "gcp_auth_begin",
            "gcp_auth_submit_code",
            "gcp_auth_status",
            "cloud_authorization_request",
            "cloud_authorization_status",
            "cloud_approval_issue",
            "cloud_approval_status",
            "cloud_apply_window_set",
            "cloud_apply_window_status",
            "gcp_list_projects",
            "gcp_billing_accounts_list",
            "gcp_list_billing_accounts",
            "gcp_billing_projects_list",
            "gcp_project_billing_info",
            "gcp_get_project_billing",
            "gcp_billing_credits_status",
            "gcp_allowlist_project",
            "gcp_allowlist_billing_account",
            "gcp_budgets_list",
            "gcp_budget_list",
            "gcp_budget_status",
            "gcp_budget_create",
            "gcp_costs_query",
            "gcp_billing_cost_summary",
            "gcp_billing_export_status",
            "gcp_billing_export_prepare",
            "gcp_quotas_list",
            "gcp_project_iam_policy",
            "gcp_project_iam_add_binding",
            "gcp_artifact_registry_list",
            "gcp_artifact_registry_create",
            "gcp_project_setup_preflight",
            "gcp_create_project",
            "gcp_link_billing",
            "gcp_enable_apis",
            "gcp_cloud_run_status",
            "gcp_cloud_run_deploy",
            "gcp_cloud_run_revisions",
            "gcp_cloud_run_traffic",
            "gcp_cloud_run_rollback",
            "gcp_logs_query",
            "gcp_secret_manager_metadata",
            "gcp_secret_manager_create_version",
            "gcp_firestore_status",
            "gcp_firestore_create_db",
            "gcp_pubsub_list",
            "gcp_pubsub_create_topic",
            "gcp_pubsub_create_subscription",
            "gcp_gemini_or_vertex_status",
            "gcp_service_health_check",
            "provider_manifest_schema",
            "provider_register_manifest",
            "provider_list_manifests",
            "provider_preflight",
            "application_get",
            "application_upsert",
            "application_add_or_update_module",
            "application_upsert_question_answer",
            "application_list_questions",
            "application_search",
            "application_attach_source",
            "application_attach_evidence",
            "application_history",
            "application_mark_submitted",
            "application_export_snapshot",
            "application_migrate_legacy_funding_application",
        ],
    },
    "voice_owner_compact": {
        "label": "voz.pcdoctor.ai — entrada compacta para modelos locales pequeños",
        "model_minimum": "small",
        "max_tools": 12,
        "tools": [
            "bootstrap_context",
            "search_memory",
            "get_context_summary",
            "route_mcp_tools",
            "ralfia_dispatch",
            "dispatch_local_agent",
            "run_service_guardian",
            "resolve_client",
            "get_server_status",
            "get_whatsapp_status",
            "local_model_health",
            "create_agent_message",
        ],
    },
    "local_self_repair": {
        "label": "Autoreparación local controlada",
        "model_minimum": "medium",
        "max_tools": 26,
        "tools": [
            "get_coordination_live",
            "bootstrap_context",
            "local_model_health",
            "route_ai_task",
            "manage_coordination_lock",
            "local_fs_policy",
            "local_fs_list",
            "local_fs_read_file",
            "local_fs_mkdir",
            "local_fs_write_file",
            "local_git_init_repo",
            "local_github_status",
            "local_project_bootstrap",
            "local_exec_inspect_repo",
            "local_exec_repo_policy_status",
            "local_exec_repo_authorize",
            "local_exec_repo_revoke",
            "local_exec_prepare_repo",
            "local_exec_acquire_lock",
            "local_exec_release_lock",
            "local_exec_create_worktree",
            "local_exec_apply_patch",
            "local_exec_write_file",
            "local_exec_run_command_allowlisted",
            "local_exec_commit_branch",
            "local_exec_report_evidence",
        ],
    },
    "server_ops": {
        "label": "Ops local servidor — cero créditos cloud",
        "model_minimum": "small",
        "max_tools": 14,
        "tools": [
            "get_coordination_live",
            "poll_agent_inbox",
            "create_agent_message",
            "ack_agent_message",
            "get_mcp_fleet_status",
            "get_unified_stack_status",
            "system_health",
            "reconcile_runtime_state",
            "run_health_watch",
            "list_ralphia_agents",
            "get_development_roadmap",
            "manage_coordination_lock",
            "local_model_health",
            "route_ai_task",
        ],
    },
    "peer_ops": {
        "label": "Peer ops — status/restart/logs .4/.5",
        "model_minimum": "small",
        "max_tools": 12,
        "tools": [
            "get_development_roadmap",
            "reconcile_runtime_state",
            "peer_ops_snapshot",
            "peer_ops_status",
            "peer_ops_logs",
            "list_peer_ops_services",
            "peer_ops_action",
            "manage_coordination_lock",
            "create_agent_message",
            "list_ralphia_agents",
        ],
    },
    "platform_sync": {
        "label": "Sync dual-nodo + clone tenant",
        "model_minimum": "small",
        "max_tools": 10,
        "tools": [
            "get_development_roadmap",
            "sync_platform_to_intel",
            "run_failover_dry_run",
            "clone_tenant_deployment",
            "reconcile_runtime_state",
            "get_mcp_fleet_status",
            "manage_coordination_lock",
            "create_agent_message",
        ],
    },
    "cloud_ops": {
        "label": "Cloud deploy ops multi-provider (dry-run safe)",
        "model_minimum": "medium",
        "max_tools": 74,
        "tools": [
            "get_development_roadmap",
            "cloud_deploy_status",
            "cloud_deploy_plan",
            "cloud_provider_status",
            "cloud_deploy_dry_run",
            "cloud_deploy_apply",
            "cloudflare_status",
            "cloudflare_prepare_hostname",
            "cloudflare_dns_upsert",
            "cloudflare_dns_delete",
            "cloudflare_waf_skip_challenge",
            "cloudflare_waf_delete_hostname_rules",
            "cloudflare_tunnel_ingress_status",
            "cloudflare_hostname_health_check",
            "reconcile_runtime_state",
            "manage_coordination_lock",
            "create_agent_message",
            "local_exec_inspect_repo",
            "get_coordination_live",
            "gcp_auth_bootstrap",
            "gcp_auth_begin",
            "gcp_auth_submit_code",
            "gcp_auth_status",
            "cloud_authorization_request",
            "cloud_authorization_status",
            "cloud_approval_issue",
            "cloud_approval_status",
            "cloud_apply_window_set",
            "cloud_apply_window_status",
            "gcp_list_projects",
            "gcp_billing_accounts_list",
            "gcp_list_billing_accounts",
            "gcp_billing_projects_list",
            "gcp_project_billing_info",
            "gcp_get_project_billing",
            "gcp_billing_credits_status",
            "gcp_allowlist_project",
            "gcp_allowlist_billing_account",
            "gcp_budgets_list",
            "gcp_budget_list",
            "gcp_budget_status",
            "gcp_budget_create",
            "gcp_costs_query",
            "gcp_billing_cost_summary",
            "gcp_billing_export_status",
            "gcp_billing_export_prepare",
            "gcp_quotas_list",
            "gcp_project_iam_policy",
            "gcp_project_iam_add_binding",
            "gcp_artifact_registry_list",
            "gcp_artifact_registry_create",
            "gcp_project_setup_preflight",
            "gcp_create_project",
            "gcp_link_billing",
            "gcp_enable_apis",
            "gcp_cloud_run_status",
            "gcp_cloud_run_deploy",
            "gcp_cloud_run_revisions",
            "gcp_cloud_run_traffic",
            "gcp_cloud_run_rollback",
            "gcp_logs_query",
            "gcp_secret_manager_metadata",
            "gcp_secret_manager_create_version",
            "gcp_firestore_status",
            "gcp_firestore_create_db",
            "gcp_pubsub_list",
            "gcp_pubsub_create_topic",
            "gcp_pubsub_create_subscription",
            "gcp_gemini_or_vertex_status",
            "gcp_service_health_check",
            "provider_manifest_schema",
            "provider_register_manifest",
            "provider_list_manifests",
            "provider_preflight",
        ],
    },
    "local_fleet": {
        "label": "Flota local PC Doctor — cero créditos cloud",
        "model_minimum": "small",
        "max_tools": 30,
        "tools": [
            "get_agent_catalog",
            "resolve_agent",
            "route_agent_request",
            "list_local_agents",
            "dispatch_local_agent",
            "run_service_guardian",
            "agent_quote_prepare",
            "agent_report_technical",
            "agent_invoice_prepare",
            "run_daily_companion",
            "agent_health_summary",
            "agent_funding_status",
            "agent_iskcon_status",
            "vero_dispatch",
            "quote_client",
            "peer_ops_snapshot",
            "reconcile_runtime_state",
            "route_ai_task",
            "local_fs_policy",
            "local_fs_mkdir",
            "local_fs_write_file",
            "local_git_init_repo",
            "local_github_status",
            "local_project_bootstrap",
            "local_exec_inspect_repo",
            "local_exec_prepare_repo",
            "local_model_health",
            "get_development_roadmap",
            "create_agent_message",
        ],
    },
    "local_fleet_compact": {
        "label": "Flota local compacta — modelos pequeños / voz",
        "model_minimum": "small",
        "max_tools": 10,
        "tools": [
            "route_mcp_tools",
            "ralfia_dispatch",
            "list_local_agents",
            "dispatch_local_agent",
            "run_service_guardian",
            "agent_quote_prepare",
            "agent_report_technical",
            "agent_invoice_prepare",
            "get_development_roadmap",
            "create_agent_message",
        ],
    },
    "local_fleet_full": {
        "label": "Flota local completa — ChatGPT/Codex",
        "model_minimum": "medium",
        "max_tools": 64,
        "tools": [
            "get_agent_catalog",
            "resolve_agent",
            "route_agent_request",
            "list_local_agents",
            "dispatch_local_agent",
            "run_service_guardian",
            "agent_quote_prepare",
            "agent_report_technical",
            "agent_invoice_prepare",
            "run_daily_companion",
            "agent_health_summary",
            "agent_funding_status",
            "agent_iskcon_status",
            "vero_dispatch",
            "quote_client",
            "peer_ops_snapshot",
            "reconcile_runtime_state",
            "route_ai_task",
            "local_fs_policy",
            "local_project_bootstrap",
            "local_github_status",
            "local_exec_inspect_repo",
            "local_exec_prepare_repo",
            "local_model_health",
            "get_development_roadmap",
            "create_agent_message",
            "gcp_auth_bootstrap",
            "cloud_authorization_request",
            "cloud_authorization_status",
            "gcp_list_projects",
            "gcp_create_project",
            "gcp_link_billing",
            "gcp_enable_apis",
            "gcp_cloud_run_status",
            "gcp_cloud_run_deploy",
            "gcp_cloud_run_revisions",
            "gcp_cloud_run_traffic",
            "gcp_cloud_run_rollback",
            "gcp_logs_query",
            "gcp_secret_manager_metadata",
            "gcp_secret_manager_create_version",
            "gcp_firestore_status",
            "gcp_firestore_create_db",
            "gcp_pubsub_list",
            "gcp_pubsub_create_topic",
            "gcp_pubsub_create_subscription",
            "gcp_gemini_or_vertex_status",
            "gcp_service_health_check",
            "provider_manifest_schema",
            "provider_register_manifest",
            "provider_list_manifests",
            "provider_preflight",
            "application_get",
            "application_upsert",
            "application_add_or_update_module",
            "application_upsert_question_answer",
            "application_list_questions",
            "application_search",
            "application_attach_source",
            "application_attach_evidence",
            "application_history",
            "application_mark_submitted",
            "application_export_snapshot",
            "application_migrate_legacy_funding_application",
        ],
    },
    "pc_doctor_daily": {
        "label": "Operación diaria PC Doctor (cotizar, informar, vigilar)",
        "model_minimum": "small",
        "max_tools": 14,
        "tools": [
            "dispatch_local_agent",
            "run_service_guardian",
            "vero_dispatch",
            "resolve_client",
            "build_client_360_snapshot",
            "list_client_documents",
            "create_quote_draft",
            "generate_quote_pdf",
            "send_quote_delivery",
            "generate_supervisor_report",
            "create_receivable_from_quote",
            "peer_ops_snapshot",
            "get_development_roadmap",
        ],
    },
    "daily_companion": {
        "label": "Compañero día a día — brief, memoria, conversación local",
        "model_minimum": "small",
        "max_tools": 16,
        "tools": [
            "route_agent_request",
            "resolve_agent",
            "get_agent_catalog",
            "run_daily_companion",
            "agent_daily_save_note",
            "generate_daily_brief",
            "search_memory",
            "save_memory",
            "get_current_state",
            "timeline",
            "route_ai_task",
            "local_model_health",
            "dispatch_local_agent",
            "local_exec_inspect_repo",
            "local_exec_prepare_repo",
            "create_agent_message",
        ],
    },
    "health_memory": {
        "label": "Historial de salud privado (PRIVATE_HEALTH)",
        "model_minimum": "small",
        "max_tools": 12,
        "tools": [
            "route_agent_request",
            "resolve_agent",
            "agent_health_save",
            "agent_health_timeline",
            "agent_health_summary",
            "save_memory",
            "search_memory",
            "timeline",
            "dispatch_local_agent",
            "create_agent_message",
        ],
    },
    "iskcon_ops": {
        "label": "Operaciones ISKCON — ent_iskcon, FFL, festivales, templo",
        "model_minimum": "small",
        "max_tools": 16,
        "tools": [
            "agent_iskcon_capabilities",
            "agent_iskcon_status",
            "agent_iskcon_domain",
            "agent_iskcon_ffl_log",
            "agent_iskcon_ffl_timeline",
            "agent_iskcon_contacts_summary",
            "agent_iskcon_dispatch",
            "create_ops_task",
            "list_ops_tasks",
            "save_memory",
            "search_memory",
            "get_funding_registry_summary",
            "list_funding_programs",
            "dispatch_local_agent",
            "create_agent_message",
        ],
    },
    "hackathon_funding": {
        "label": "Hackathons + créditos/grants — correo + registry",
        "model_minimum": "medium",
        "max_tools": 35,
        "tools": [
            "route_agent_request",
            "resolve_agent",
            "get_agent_catalog",
            "agent_hackathon_status",
            "agent_hackathon_scan_emails",
            "agent_funding_status",
            "agent_funding_scan_emails",
            "agent_funding_register_from_email",
            "get_funding_registry_summary",
            "list_funding_programs",
            "list_funding_applications",
            "search_email_archive",
            "trigger_email_poll",
            "dispatch_local_agent",
            "create_ops_task",
            "get_development_roadmap",
            "create_agent_message",
            "get_dev_backlog_summary",
            "list_dev_backlog",
            "capture_backlog_item",
            "finalize_session_handoff",
            "generate_agent_activity_report",
            "list_recent_agent_activity",
            "application_get",
            "application_upsert",
            "application_add_or_update_module",
            "application_upsert_question_answer",
            "application_list_questions",
            "application_search",
            "application_attach_source",
            "application_attach_evidence",
            "application_history",
            "application_mark_submitted",
            "application_export_snapshot",
            "application_migrate_legacy_funding_application",
        ],
    },
    "ralfia_hub": {
        "label": "RalfIA orquestador — ve todo, enruta cualquier agente",
        "model_minimum": "medium",
        "max_tools": 16,
        "tools": [
            "ralfia_dispatch",
            "ralfia_status",
            "get_agent_catalog",
            "resolve_agent",
            "route_agent_request",
            "invoke_agent",
            "list_ralphia_agents",
            "list_local_agents",
            "get_coordination_live",
            "bootstrap_context",
            "dispatch_local_agent",
            "create_agent_message",
            "get_development_roadmap",
            "list_ops_tasks",
        ],
    },
    "product_catalog": {
        "label": "Product Intelligence + catálogo multi-proveedor",
        "model_minimum": "medium",
        "max_tools": 5,
        "tools": [
            "product_intelligence",
            "list_inventory",
            "upsert_inventory_item",
            "resolve_party",
            "extract_fields_from_media",
        ],
    },
    "quoteops": {
        "label": "QuoteOps Build Week end-to-end",
        "model_minimum": "medium",
        "max_tools": 15,
        "tools": [
            "quoteops_start_or_continue_mission",
            "quoteops_get_mission",
            "quoteops_upsert_commercial_profile",
            "quoteops_get_sourcing_recommendations",
            "quoteops_add_supplier_offer",
            "quoteops_record_extracted_evidence",
            "quoteops_review_extracted_evidence",
            "quoteops_review_catalog_draft",
            "quoteops_update_decision_brief",
            "quoteops_upsert_configuration_alternative",
            "quoteops_review_configuration_alternative",
            "quoteops_select_package",
            "quoteops_update_quote",
            "quoteops_approve_quote",
            "quoteops_register_delivery",
        ],
    },
}


def validate_profiles() -> dict[str, Any]:
    """Validate profile contracts against the live catalog definition.

    Profiles are a public contract for small models. Publishing an unknown tool
    or exceeding ``max_tools`` silently defeats the purpose of the projection.
    """
    catalog_names = set(tool_catalog.ALL_MCP_TOOL_NAMES)
    errors: list[dict[str, Any]] = []

    for profile_name, conf in PROFILES.items():
        tools = list(conf.get("tools") or [])
        max_tools = int(conf.get("max_tools") or 0)
        duplicates = sorted({name for name in tools if tools.count(name) > 1})
        unknown = sorted(set(tools) - catalog_names)

        if max_tools <= 0:
            errors.append({"profile": profile_name, "code": "invalid_max_tools", "value": max_tools})
        if len(tools) > max_tools:
            errors.append(
                {
                    "profile": profile_name,
                    "code": "tool_limit_exceeded",
                    "tool_count": len(tools),
                    "max_tools": max_tools,
                }
            )
        if duplicates:
            errors.append({"profile": profile_name, "code": "duplicate_tools", "tools": duplicates})
        if unknown:
            errors.append({"profile": profile_name, "code": "unknown_tools", "tools": unknown})

    return {
        "ok": not errors,
        "profiles_version": PROFILES_VERSION,
        "profile_count": len(PROFILES),
        "errors": errors,
    }


def list_profiles(*, for_model: str | None = None) -> dict[str, Any]:
    fp = catalog_fingerprint()
    validation = validate_profiles()
    profiles_out = {}
    for key, conf in PROFILES.items():
        tools = list(dict.fromkeys(conf["tools"]))
        profiles_out[key] = {
            **{k: v for k, v in conf.items() if k != "tools"},
            "tools": tools,
            "tool_count": len(tools),
            "profile_pin": f"{PROFILES_VERSION}:{key}:{fp['tool_names_hash_short']}",
        }
    log_routing_trace(
        {
            "event": "list_profiles",
            "for_model": for_model,
            "profiles": list(profiles_out),
            "catalog_version": fp["catalog_version"],
        }
    )
    return {
        "ok": True,
        "profiles_version": PROFILES_VERSION,
        "catalog_version": fp["catalog_version"],
        "catalog_pin": fp["pin_hint"],
        "tool_count_global": fp["tool_count"],
        "profiles": profiles_out,
        "validation": validation,
        "note": (
            "Perfiles = proyección recomendada. El endpoint MCP legacy sigue listando todas las tools. "
            "Si diagnose_mcp_session marca stale: refrescar connector + reautorizar OAuth."
        ),
        "stale_client_guidance": {
            "if_tool_count_lt_server": "needs_refresh_connector",
            "if_catalog_version_mismatch": "needs_refresh_connector + pin catalog_pin",
            "if_oauth_errors": "needs_reauthorize_oauth",
        },
    }


def get_profile(name: str) -> dict[str, Any]:
    allp = list_profiles()
    conf = (allp.get("profiles") or {}).get(name)
    if not conf:
        return {"ok": False, "error": "unknown_profile", "available": sorted(PROFILES)}
    return {"ok": True, "profile": name, **conf, "catalog_pin": allp["catalog_pin"], "profiles_version": PROFILES_VERSION}
